#!/usr/bin/env bash
# Scripts that are generated by other scripts still have to be valid shell.
# A syntax error inside cloud-init or inside the backup generator would only
# show up on a live server, so it is checked here instead.
set -uo pipefail
. "$(dirname "$0")/../lib.sh"
load_libs

echo "unit: embedded and generated scripts"

WORK="$(mktemp -d "${TMPDIR:-/tmp}/gho-embed.XXXXXX")"

# --- the cloud-init bootstrap script ---------------------------------------
# The block scalar body is indented by exactly six spaces; strip that and we
# have the file that will land at /usr/local/sbin/gho-bootstrap.sh.
awk '
	/^  - path: \/usr\/local\/sbin\/gho-bootstrap.sh$/ { found = 1 }
	found && /^    content: \|$/ { capture = 1; next }
	capture && /^[^ ]/ { capture = 0 }
	capture && /^  - path:/ { capture = 0 }
	capture && /^runcmd:/ { capture = 0 }
	capture { sub(/^      /, ""); print }
' "${REPO_ROOT}/templates/cloud-init.yaml" >"${WORK}/bootstrap.sh"

assert_ok "the bootstrap script was extracted" test -s "${WORK}/bootstrap.sh"
assert_ok "the extracted bootstrap script is valid bash" bash -n "${WORK}/bootstrap.sh"
assert_ok "the bootstrap script sets strict mode" \
	bash -c "grep -q 'set -Eeuo pipefail' '${WORK}/bootstrap.sh'"
assert_ok "the bootstrap script traps errors" \
	bash -c "grep -q \"trap 'status failed false' ERR\" '${WORK}/bootstrap.sh'"

# Placeholders are rendered before this ever runs, so the extracted copy still
# has them; that is what proves the renderer has something to substitute.
assert_ok "the bootstrap script references the rendered hostname" \
	bash -c "grep -q '__TS_HOSTNAME__' '${WORK}/bootstrap.sh'"

# --- the generated nightly backup script ------------------------------------
sed -n '/<<BACKUP$/,/^BACKUP$/p' "${REPO_ROOT}/remote/configure-backups.sh" |
	sed -e '1d' -e '$d' \
		-e 's|${BACKUP_DIR}|/var/backups/ghost|g' \
		-e 's|${GHOST_DIR}|/var/www/ghost|g' \
		-e 's|${ADMIN_USER}|ghostops|g' \
		-e 's|${RETENTION}|7|g' \
		-e 's|\\\$|$|g' >"${WORK}/ghost-backup.sh"

assert_ok "the backup script was extracted" test -s "${WORK}/ghost-backup.sh"
assert_ok "the generated backup script is valid bash" bash -n "${WORK}/ghost-backup.sh"
assert_ok "the backup script sets strict mode" \
	bash -c "grep -q 'set -Eeuo pipefail' '${WORK}/ghost-backup.sh'"
assert_ok "the backup script uses a 0600 defaults file for MySQL credentials" \
	bash -c "grep -q 'defaults-extra-file' '${WORK}/ghost-backup.sh'"
assert_ok "the backup script never puts the password on a command line" \
	bash -c "! grep -qE 'mysqldump[^|]*-p[A-Za-z0-9$]' '${WORK}/ghost-backup.sh'"
assert_ok "the backup script includes the content directory" \
	bash -c "grep -q 'content.tar.gz' '${WORK}/ghost-backup.sh'"
assert_ok "the backup script enforces retention" \
	bash -c "grep -q 'RETENTION' '${WORK}/ghost-backup.sh'"
assert_ok "the backup script fails on an empty archive" \
	bash -c "grep -q 'backup archive is empty' '${WORK}/ghost-backup.sh'"

# --- remote scripts refuse to run as the wrong user / with bad input --------
assert_ok "install-ghost.sh requires a domain" \
	bash -c "grep -q 'domain required' '${REPO_ROOT}/remote/install-ghost.sh'"
assert_ok "configure-backups.sh validates its retention argument" \
	bash -c "grep -q 'retention must be a small integer' '${REPO_ROOT}/remote/configure-backups.sh'"
assert_ok "the MySQL password generator emits only alphanumerics" \
	bash -c "grep -q \"tr -dc 'A-Za-z0-9'\" '${REPO_ROOT}/remote/install-ghost.sh'"
assert_ok "SQL statements come from a file, never a command line" \
	bash -c "grep -q 'sudo mysql --batch --raw <' '${REPO_ROOT}/remote/install-ghost.sh'"

rm -rf "$WORK"
finish
